name: CI_blindml

on: push

jobs:
  basic-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: run test
      run: |
        pip install -r requirements.txt --extra-index-url https://pypi.anaconda.org/scipy-wheels-nightly/simple
        ./quick-test.sh

